// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbSgNhzRaGvUd7e0pYvXJ4eAPMOJ4nc7M',
    appId: '1:823314898677:web:91971ccd74f842cc372fbc',
    messagingSenderId: '823314898677',
    projectId: 'moneygetsmoney-42cdc',
    authDomain: 'moneygetsmoney-42cdc.firebaseapp.com',
    storageBucket: 'moneygetsmoney-42cdc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEjgZI09h8jDfn5iZ70oUU-eRDhs8fdcc',
    appId: '1:823314898677:android:f7e6d82e26fd6bd8372fbc',
    messagingSenderId: '823314898677',
    projectId: 'moneygetsmoney-42cdc',
    storageBucket: 'moneygetsmoney-42cdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgS-vY9UF-yMfSHj0jiAP6VtusuHzIUXA',
    appId: '1:823314898677:ios:fe6c2c6f6d8cc7fb372fbc',
    messagingSenderId: '823314898677',
    projectId: 'moneygetsmoney-42cdc',
    storageBucket: 'moneygetsmoney-42cdc.firebasestorage.app',
    iosBundleId: 'com.example.moneyGetsMoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgS-vY9UF-yMfSHj0jiAP6VtusuHzIUXA',
    appId: '1:823314898677:ios:fe6c2c6f6d8cc7fb372fbc',
    messagingSenderId: '823314898677',
    projectId: 'moneygetsmoney-42cdc',
    storageBucket: 'moneygetsmoney-42cdc.firebasestorage.app',
    iosBundleId: 'com.example.moneyGetsMoney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbSgNhzRaGvUd7e0pYvXJ4eAPMOJ4nc7M',
    appId: '1:823314898677:web:997d3efc3dffe404372fbc',
    messagingSenderId: '823314898677',
    projectId: 'moneygetsmoney-42cdc',
    authDomain: 'moneygetsmoney-42cdc.firebaseapp.com',
    storageBucket: 'moneygetsmoney-42cdc.firebasestorage.app',
  );
}
